getsentry/responses

- README.rst
- responses.py
- test_responses.py
I expect from my testing tools to detect inconsistencies and unpredictable behaviour.
This is why I would like that `responses` helps me to detect request that has not been performed unlike it should.
I implemented it in a way that is backward compatible, but I'm in favour of enabling this behaviour by default.
> Raise if requests are not performed as expected

- responses.py
This PR adds the method name to "connection refused" errors to aid debugging, as (for example) it's quite easy when duplicating a previous test as the basis for a new test to forget to change the method (e.g. `put` to `post`).
> Feature: show method for "connection refused" messages

- responses.py
I noticed that the keyword arguments can be passed by position instead of passing them by keyword.
It simplifies sligthly the function.
> Simplify `get_wrapped` function

- responses.py
- test_responses.py
When raising a ConnectionError, the requests module sets the error's request attribute to the current request. The responses module should do the same.
Sample Script:
```
import requests
import responses
def req():
try:
requests.get('http://example.zalando.net')
except Exception as e:
return(e.request)
else:
assert False
print('Real:          ', req())
print('With responses:', responses.activate(req)())
```
Output:
```
Real:           <PreparedRequest [GET]>
With responses: None
````
> Fix ConnectionError Emulation

- README.rst
- responses.py
- test_responses.py
It's a lot more convenient than writing a JSON-formatted string, and it automatically sets the Content-Type header for you!
> Allow passing a JSON body to `responses.add`

- setup.py
This change indicates that the package supports Python 3. This ensures it'll pass automated checks such as https://caniusepython3.com/project/responses .
This would be very useful when automatically gathering all packages that do not yet support Python 3 in the projects that I'm working on.
> Indicate Python 3 support in setup.py

- responses.py
- test_responses.py
Currently, is not possible to pass an object that evaluates to `False` as a `json` argument:
```python
responses.add(responses.GET, url, json=[])  # or `json={}`
req = requests.get(url)
assert req.headers['Content-Type'] == 'application/json'  # fails!
> Allow empty list/dict as json object

- CHANGES
I was using requires.io to bring our dependencies up to date, and in so doing I noticed that the changelog for responses hasn't been updated for the 0.5.1 release.
Looking at the diffs shows that the only user-facing change was to packaging:
https://github.com/getsentry/responses/compare/0.5.0...0.5.1
However it makes sense to update CHANGES to save others having to audit this by hand too :-)
I've also noted changes on master, since it will make it quicker to release the next version, if the changelog is already up to date:
https://github.com/getsentry/responses/compare/0.5.1...c62fd372fff0bd77335bb0e7a0569aa056226521
> Update changelog for changes since 0.5.0

- README.rst
Describe how to use a secret feature in the responses library that I often (and otheres) find use for.
I created this since there doesnt seem to be any intention of merging #101 in, so it would be good to document how this is done without explicit support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/responses/123)
> Add section to README about using multiple responses

- .travis.yml
This PR skips linting for Python 2.6, which isn't supported by flake8 anymore.
> Skip `make lint` for Python 2.6

- responses.py
- test_responses.py
Currently when using responses as a context manager with `assert_all_requests_are_fired`, any exception raised inside the `with` block will be swallowed if not all requests have been fired. This can obscure issues in the code unrelated to its requests behavior.
This pull request bypasses responses' assertion that all requests were fired when exiting the context manager due to a raised exception.
> Reraising exceptions when exiting context manager

- responses.py
- test_responses.py
See #130 
> The field reason is missing from the mocked request. It is usually set to HTTP status code's readable name (eg. "OK" "Not Found")
> 
> This make some libraries, like requests_toolbelt dumping unhappy.
> Added reason to mocked HTTPResponse

- responses.py
- test_responses.py
Recently I had to write some tests against an API endpoint which does not return a Content-Type header in the response.  This is bad practice on the part of the API in question of course, but currently it is impossible to simulate this with `responses`.
> allow to return a response with no content-type header

- CHANGES
- README.rst
- responses.py
- test_responses.py
First off- this package is AMAZING. Thank you! You have greatly simplified my testing work, and have helped me move a large project so much closer to offline testing for everything. 
Unfortunately, the existing `responses` can't cover all our code and test cases easily. I needed the ability to either further-process or identify mocked responses and handle them slightly differently in a few situations. 
This PR is what I'm using locally and would like to offer upstream.  It simply adds a `response_callback` option, which can be used to perform additional processing on a response after generation.
A simple example is adding an attribute to note the response has been mocked.
An extended use-case: A package that I've open-sourced uses `requests` to fetch data, and uses a hook via mixins to …
> adding response_callbacks to improve compatibility

- .pre-commit-config.yaml
- .travis.yml
- Makefile
- README.rst
- responses.py
- setup.cfg
- setup.py
- test_responses.py
```python
responses.add(Response('GET', 'http://example.com'))
```
> Various improvements and refactor

- responses.py
- test_responses.py
The only change in behaviour when setting `assert_all_requests_are_fired=True` should be the expected assertion. 
Prior to this PR, the url would be removed, thus a subsequent call to the same url hit the next match, or make a _real_ request if there was no match.
This is a breaking change as some users could be relying on the old behaviour.
> Don't remove urls when assert_all_requests_are_fired=True

- README.rst
Looks like someone used markdown syntax in an RST document. This corrects that so that the README doesn't look messed up.
> Fix README.rst syntax

- responses.py
- test_responses.py
HTTPResponse.reason can be left blank. There is no reason to fail
for status codes like 418. It worked before 0.6.
> fix: allow returning arbitrary status codes

- responses.py
- test_responses.py
Fixes a bug (#170) where the list of matches is incorrectly updated after a match, leading to issues with multiple responses.
I'm not entirely sure why the list of matches is being rotated in the first place, so this may create some other unwanted side effect.
> Issue #170: Fix bug with handling multiple matches

- responses.py
`inspect.getargspec()` is deprecated in Python 3. Annotations break when using a type hint ('ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them'). Using `inspect.getfullargspec()` looks to not be a big change.
> Use inspect.getfullargspec() in Python 3

- responses.py
- test_responses.py
Fixes #175 by doing some validation during `_url_matches`
At first it was during BaseRequest init, but that broke some things, so I changed it. Now the tests pass and I added another one to validate URLs with unicode in the path, not just the query string.
Note that a test like this
```python
import requests
import responses
@responses.activate
def test_simple():
responses.add(responses.GET, 'https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे',
status=200)
resp = requests.get('https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे')
assert len(responses.calls) == 1
assert responses.calls[0].request.url == 'https://hi.wikipedia.org/wiki/दिलवाले_दुल्हनिया_ले_जाएंगे'
assert responses.calls[0].response.status_code == 200
test_simple()
```
will fail the second-to-last assertion. But …
> Adds unicode handling to _url_matches,  fixes issue #175

- responses.py
- setup.py
- test_responses.py
Earlier versions would have URLs like http://www.संजाल.भारत/hi/वेबसाइट-डिजाइन result in a connection error. This PR fixes that by encoding unicode in domain names and TLDs correctly when matching URLs.
> Add support for unicode in domain names and tlds

- responses.py
According to RequestMock.add, one can use any `BaseResponse` subclass,
and `BaseResponse` only requires implementing `get_response`.
However when one tries to do so `_on_request` blows up as it *always* checks for `match.stream`, which `BaseResponse` doesn't implement, and thus it blows up until one sets that attribute.
Adding `stream = False` at the class level should fix it and not break anything.
> Add stream attribute to BaseResponse

- README.rst
* All headers are now separated by 2 blank lines.
* Imports in examples are separated by 1 blank line.
* All ReST constructs are indented to four spaces.
* Tabs are converted to 4 spaces.
* Trailing whitespace is trimmed.
> Patch up the README

- responses.py
This one is pretty straightforward, some request-settings are not getting passed along for stuff like proxies and certificates.
In my particular use-case the fix is essential because a SOCKS proxy is the only way to access the external resource. (Without `socks5h://` I can't even resolve the internal hostname.)
> Fix pass-thru requests losing additional settings

- README.rst
Sometimes you need to register the same callback function multiple time, but with slightly different behavior (ex. a different username in the response). Being able to pass arguments to the callback function makes for less code duplication.
> Alow extra keyword arguments to be passed to the callback function

- README.rst
- responses.py
- test_responses.py
Previously, adding a response with a query string without also setting
match_querystring=True would provide confusing results, see #211.
This commit changes the argument's default value to consider the URL and
automatically enable match_querystring if a query string is detected in
the response.
> Change match_querystring default to consider URL

- responses.py
"`from collections import Sequence, Sized`" produces a `DeprecationWarning` under Python 3.7 with the message:
> Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
This patch eliminates this warning by importing from `collections.abc` instead, falling back to `collections` only if that fails (i.e., if running under Python < 3.3).
> Import collections ABCs from collections.abc if possible

- .travis.yml
- responses.py
- setup.py
- test_responses.py
This pull request addresses issue #186 by using the [biscuits](https://github.com/pyrates/biscuits) package instead of [cookies](https://gitlab.com/sashahart/cookies/) when on Python >= 3.4. Biscuits does not support Python < 3.4 so the original behavior is maintained there.
> use biscuits on Python 3, cookies on Python 2

- tox.ini
Without this, running `tox` fails because none of the test dependencies are installed.
> Install test extras in tox

- responses.py
- setup.py
Instead of adding a dependency to parse cookies in python3 we can use stdlib features.
> Don't use a dependency to parse cookies in py3

- responses.py
- test_responses.py
Fixes #216. Use Python 3's `inspect.signature` to replace the argument specification in the wrapper function.
> Fix warnings from formatargspec

- responses.py
- test_responses.py
It now works like regular response mocking where a body that
is an Exception subclass triggers that exception to be raised.
Support for the existing undocumented callback-only behavior
is retained but a deprecation warning issued. Tests are added
for both of these cases.
Fixes #234
> Fix callback exception mocking.

- README.rst
@getsentry I've really been digging `responses`! I've found it easier to work with than `unittest.mock`. Thanks for providing it!
Please consider this small PR to remove a trailing comma I noticed while going through the README.
> removed extra comma in docs

- README.rst
Earlier documentation does state that a compiled regex can
be passed to the `url` argument, but it's easy to miss.
> Add documentation on regex-matching

- setup.py
For Python 2.7, mock is a hard requirement and so should be listed in `install_requires`.
Update system requirement to the more accurate: `python_version < '3.3'`. It no longer references unsupported Python 2.6.
Alphabetize the install_requires list.
> Clean up 'mock' requirement declaration in setup.py

- README.rst
- responses.py
Referencing https://github.com/getsentry/responses/issues/252#event-2089058954 this PR adds a property that can be used to check the `_matches` property on the `RequestsMock`. Also updated the documentation to add some detail around replacing/removing registered responses
> Added matches property to RequestMock. Updated documentation for modifying responses

- responses.py
Fixes #225 
Changed the message to:
1. show that the Connection was refused by Responses
2. Show that METHOD URL doesn't match with Responses Mock
> Issue 225: Connection Error message mentions Responses

- MANIFEST.in
- setup.py
test_responses.py is moved to MANIFEST.in to be included
in the sdist, without being an installation target.
Fixes https://github.com/getsentry/responses/issues/256
> setup.py: Remove test_responses.py

- responses.py
- test_responses.py
This PR normalizes the return value of `_cookies_from_headers()` so that the function consistently returns URL-quoted version of non-ASCII characters set as cookie values.
The issue is that when a cookie value involves non-ASCII chars being URL-quoted, `cookies.Cookies.from_request()` appears to return unquoted chars whereas `http.cookies.SimpleCookie.load` does not. This inconsistency makes it tedious to write tests on cookies with non-ASCII characters.
> Return quoted value consistently

- test_responses.py
Pytest 5.0.0 changed ExceptionInfo object's str() to returns the same as repr().
(See, item #5412 of https://docs.pytest.org/en/latest/changelog.html#pytest-5-0-0-2019-06-28)
This patch fixes the test failure by comparing expectation with str() result of
ExceptionInfo's value member instead of object itself.
Signed-off-by: Brandon Hong <brandon.hong@intel.com>
> Fix testcase test_assert_all_requests_are_fired failure

- setup.py
pytest after 4.6 does not support Python 3.5 and earlier, causing tests run under Python 2.7 to fail with syntax errors in pytest.  Update the pytest requirement to use the appropriate version depending on the version of Python in use.
> Fix tests on Python2.7

- .vscode/settings.json
- setup.py
The fix in #284 does not allow for point releases of pytest 4.6 to be installed, only 4.6.0.
According to [pytest.org](https://pytest.org/en/latest/py27-py34-deprecation.html):
> until January 2020 the pytest core team plans to make bug-fix releases of the pytest 4.6 series by back-porting patches to the 4.6-maintenance branch that affect Python 2 users.
> 
> After 2020, the core team will no longer actively backport patches, but the 4.6-maintenance branch will continue to exist so the community itself can contribute patches. The core team will be happy to accept those patches and make new 4.6 releases until mid-2020.
So pytest 4.6 will continue to receive patches for Python 2 support even past mid-2020, just not by the core contributors.
This allows for pytest of any version less than …
> Update pytest requirements to allow for 4.6 point releases

- responses.py
Generating globals dynamically makes the library impossible to analyze by code intelligence tools (e.g.: Pycharm).
This should help the users navigating around the library without having to resort to the documentation.
> Do not generate globals dynamically

- responses.py
- test_responses.py
Cookie handling in responses is currently broken.  There have been a couple of PRs created to attempt to address this (PR #110, PR #273), but they do not handle `Set-Cookie` headers correctly.  In particular, a `Set-Cookie: session_id=12345; a=b; c=d` header should only create a `session_id` cookie, and _not_ create `a` or `c` cookies.  Multiple cookies are created using multiple `Set-Cookie` header lines, which means that the existing dict-based implementation cannot handle that.
This PR fixes the response objects to contain the additional members that the `requests` module relies on for cookie handling so that `responses` doesn't have to deal with it explicitly, uses `HTTPHeaderDict` to support multiple `Set-Cookie` headers, updates the existing cookie testcase to expect the correct …
> Fix cookie handling

- responses.py
- test_responses.py
* Add a shim object to remove the dependency on newer versions of urllib3.
* The `add_callback()` method has a parameter for setting the content-type. However, if the callback sets the content-type that value should be preferred and not merged with the parameter value.
Fixes #289 #290
> fix: Fix compatibility with urllib3, and add_callback regression

- .travis.yml
The pre-commit dependencies no longer install in python 3.4. Python3.4
is pretty old and has low usage as well.
> Remove tests for Python 3.4

- responses.py
When a request doesn't match the responses mock the error message isn't
very helpful. It tells you the request that was made which doesn't match
any mock, but it doesn't show you what responses have been registered.
This PR shows the request that has been made together with registered
responses. It makes it easier to spot why a test is failing because you
can compare the request with the mocks side by side.
Prior output:
```
requests.exceptions.ConnectionError: Connection refused by Responses: GET https://graph.facebook.com/v5.0/search?access_token=testac&type=adinterestvalid&interest_fbid_list=%5B%22123%22%5D doesn't match Responses Mock
```
New output:
```
requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.
Request:
-GET …
```
> Improve ConnectionError message

- README.rst
Now the line contains (``) by mistake:
```
You can see params passed in the original ‍‍``request`` in ‍‍``responses.calls[].request.params``:
```
This patch fixed the formating. Here is the real diff:
```diff
-You can see params passed in the original <U+200D><U+200D>``request`` in <U+200D><U+200D>``responses.calls[].request.params``:
+You can see params passed in the original ``request`` in ``responses.calls[].request.params``:
```
> Fixed formating in README.

- responses.py
- test_responses.py
Was looking over the code coverage report and added some missing test cases:
* `BaseResponse.matches()` distinguishing on method
* `BaseResponse._url_matches_strict()` when the number of params is the same but the keys don't match
* `_handle_body()` when the body is a BufferedReader from opening a file handle
The third commit here actually simplifies the comparison in `BaseResponse._url_matches_strict()` to a straight list comparison - it doesn't make sense to compare length and then directly compare the contents of the tuples, unless this is leftover from some old dict comparison code?
> Improve code coverage

- responses.py
- test_responses.py
Added a test to return a unicode body and noticed this wasn't working as
the charset wasn't being set. This also highlighted that Response
converts unicode to bytes twice, once in the constructor and once in the
call to _handle_body(), so the conversion in the constructor has been
removed.
There's possibly a similar bug in CallbackResponse too.
> Fix bug in handling unicode body

- responses.py
- test_responses.py
Using a simple replace when parsing the params results in an error when there's some path present.
For example, without this fix the new test would break with something like:
```python
AssertionError:
{'/some/path?hello': 'world', 'example': 'params'}
{'example': 'params', 'hello': 'world'}
```
> Fix params parsing

- .travis.yml
- test_responses.py
- tox.ini
Python 3.9 release is on October 5, 2020.
> Added Py39 support

- setup.py
We have some failed tests in #329 with this error message:
`pkg_resources.VersionConflict: (pytest 4.3.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=4.6'))`
And, Here is from `pytest-cov 2.10.0`  Changelog:
`Removed legacy pytest support. Changed setup.py so that pytest>=4.6 is required.`
> Updated pytest minimum required version.

- setup.py
This upgrades urllib3 to a version that provides the cookie interfaces that this library depends on. Earlier versions lack a get_all() method on HTTPHeaderDict
Refs #292
> Add requirement for urllib3

- responses.py
- test_responses.py
This approach lets users match on POSTed parameters - it includes two matchers for urlencoded and JSON encoded parameters and leaves open the possibility of matching on params encoded in other ways:
```
responses.add(
method=responses.POST,
url="http://example.com/",
body="one",
post_params_matcher=responses.json_params_matcher(
{"page": {"name": "first", "type": "json",}}
),
)
responses.add(
method=responses.POST,
url="http://example.com/",
body="two",
post_params_matcher=responses.urlencoded_params_matcher(
{"page": "second", "type": "urlencoded"}
),
)
```
> Add post params with custom matchers

- responses.py
- test_responses.py
If there was no body sent in the original request it comes into the matcher as `None`.
> Allow matching on empty request body

- responses.py
- test_responses.py
After incorporating https://github.com/getsentry/responses/pull/301, responses can return requested parameters by `responses.calls[].request.params`, but it doesn't support multiple values for the same parameter for now.
Although there is no standard about the multiple values for the same request parameter, requests can accept list as value of `params` (ref. [Passing Parameters In URLs](https://requests.readthedocs.io/en/master/user/quickstart/#passing-parameters-in-urls)), so I feel it is better to handle it in the same way.
> Allow request.params to have multiple values for the same key

- README.rst
Fix the `test_calc_api()` example in "Matching Request Parameters"
- `body` paramater of `responses.add()` does not accept arguments of type
`int`. Changed to `str`.
- Values in the request parameters given to
`responses.urlencoded_params_matcher()` must be of type `str`. Otherwise,
`ConnectionError` is thrown, because of not matching parameters.
> Documentation: Fix an examples in README.rst

- responses/__init__.py
- responses/__init__.pyi
- responses/test_responses.py
- setup.py
Add type stubs for the library as a separate stub file which means we can
use the python 3 syntax, with the downside of having to keep them in
sync with the source.
I ran [monkeytype][1] and [stubgen][2] over responses.py and combined the
results manually.
I had to move the module into a package for the types to work.
see: https://www.python.org/dev/peps/pep-0561/#packaging-type-information
Fixes #339
https://www.python.org/dev/peps/pep-0561/
[1]: https://github.com/Instagram/MonkeyType
[2]: https://mypy.readthedocs.io/en/stable/stubgen.html
> Add type stubs

- responses/__init__.pyi
Master branch and the later PRs were failing with `mypy` error 
```
Module has no attribute "upsert"  [attr-defined]
```
I added the stub in the `__init__.pyi` file to solve it and get our checks green again.
> Fix mypy lint failure by adding 'upsert' to mypy stubs

- responses/__init__.pyi
Since the type stub is not covered by the automated tests, I decided to change as little as possible. The new type hints for the callback should match with [how the callback is invoked and used](https://github.com/getsentry/responses/blob/master/responses/__init__.py#L445), though I have only tested it on a project I'm working on that makes use of the responses library.
EDIT: This should fix #379
> Fix erroneous typing for callback function

- responses/__init__.pyi
This method just takes in an optional dict. The implementation parses the json and compares the result. If we wanted to get really specific we could put in something more specific but the current type is just incorrect.
I'm very open to being wrong here but this is what im seeing in my testing
> Fix matches types

- responses/__init__.py
- responses/test_responses.py
This addresses the fact that currently URLs are not matched using [RFCC-3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2) compliant host-names. When adding a mock URL such as `http://some-URL-HERE`, then we should expect that both `http://some-URL-HERE` and `http://some-url-here` should pass when submitting requests. Per the RFC:
> The host sub-component is case-insensitive.
> rfc compliant url logic

- README.rst
- responses/__init__.py
- responses/__init__.pyi
- responses/test_responses.py
To be correct, the Content-Length header must be calculated from the
binary representation of the body. This is calculated as late as
possible by calling _handle_body(), and this is all done privately
within the module. Therefore, it's easiest if this is done in a
centralised place as late as possible by this module.
Every attempt I made at implementing this by extended the relevant
code just resulted in oodles of unnecessarily duplicated code compared
to what is possible by just integrating it directly.
I know this was previously tackled six years ago in #70. In that PR,
the concern was that the header was being added unconditionally. I
have mitigated this problem in my PR by controlling the new behaviour
with a flag. There are still plenty of situations where you wouldn't
want the …
> Add flag to allow automatic calculation of the Content-Length header

- CHANGES
`query_param_matcher` does not contain `s`.  But `json_params_matcher` and `urlencoded_params_matcher` do.
> Fix names and path to matchers in changelog

- README.rst
CI is moved to GH Actions, remove travis badge
> remove travis badge

- responses/__init__.py
- responses/test_responses.py
Opposite to #396 we do not need to raise an exception.
Exception is raised directly by `requests` module
If `responses` selected this response as a match to request, then such response should be treated the same way as real response. That means it should reraise/pass all exceptions occurred in HTTP libraries. This will be an expected behavior
I made some research on `requests` and it looks like they wanted to add a new argument `enforce_content_length` to `request`, so far it is on hold till version 3.0, I added a comment in docstrings in tests
Closes #394
> handle ChunkedEncodingError

- CHANGES
- responses/__init__.py
I'd like to drop python 2.7 support in a future release. 0.17.0 will be the last version of responses to support python 2.7
> Add deprecation warning for python 2.7

- README.rst
The signature of this function is:
https://github.com/getsentry/responses/blob/5799ff68ebc00a2d0faa605136862614cf3a2f88/responses/matchers.py#L234
However, in the README example, the order is reversed which can cause confusion.
> docs: multipart_matcher argument order in example

- .craft.yml
- .github/workflows/ci.yml
- CHANGES
- README.rst
- responses/__init__.py
- responses/matchers.py
- responses/test_matchers.py
- responses/test_responses.py
- setup.py
- tox.ini
See EOL matrix: https://endoflife.date/python
2.7, 3.5, 3.6 are all EOL
remove SIX module completely
update setup.py
update tox
compared to #442:
python 3.5 and 3.6 are removed as EOL
completely removes `six` module
full code coverage
> Clean up python 2.7, 3.5, 3.6

- responses/__init__.pyi
- responses/test_responses.py
The typestubs for requests and urllib3 have been updated but they are not complete and cause errors for us.
> fix(build) Fix new mypy errors caused by typestub updates

- CHANGES
- responses/__init__.py
Per the discussion in #467 - this field is no longer used anywhere, so should be safe to remove.
All tests still pass after this change (locally..)
> Remove unused field

- .github/workflows/ci.yml
- setup.py
basically, we always run on the same version of requests. Just remove redundant pipeline.
if in some time requests 3.X will come, we can update. So far requests 3 project is frozen and is not updated since 4 years.
Even if it will come, we will need to test it first, before releasing to wider audience. Thus, fix `requests` version in `setup.py`
> remove parallel requests branch test

- CHANGES
- responses/__init__.py
- responses/test_responses.py
When both the `content_type` keyword argument and the `Content-Type` header are defined we have an ambiguous set of parameters. Raise an error to let the developer known they have made an invalid method call.
Fixes #483
> Fix duplicate content-type silently failing

- responses/test_responses.py
- setup.py
pipe on master failed: https://github.com/getsentry/responses/runs/5068593004?check_suite_focus=true
new version of pytest was released, now we cannot check warns with None, there is a new method:
https://docs.pytest.org/en/7.0.x/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests
> fix test with warnings

- responses/test_responses.py
I still see the issue in pipeline
https://github.com/getsentry/responses/runs/5112676859?check_suite_focus=true
I think wrap `_real_send` will resolve the issue. Basically, only when `_real_send` is called we mock it, that ensures that passthru worked. 
@markstory 
objections ?
> tests: wrap passthru inside another mock

- responses/__init__.py
- responses/test_responses.py
A couple of changes related to passthrus:
`responses.passthru_prefixes` is always empty because it is a value type that is captured when the responses module is loaded. I've fixed this by making passthru_prefixes a mutable list. Of course, this will allow users to add things directly to the list. The downsides of this seem minimal, but I'm happy to fix this in another way if we think it's important to maintain immutability.
I also added some logging of passthrus when there is no match. I found this helpful for debugging.
> Add logging of passthrus when there's no match

- MANIFEST.in
This help Linux distro packaging as packagers usually use the test suite to they are shipping only functional releases to users.
This is likely due to commit 8a8f3422f93434c766f02fd0f1354c27ef538e25 by @beliaev-maksim (#474).
> ensure tests are present in sdist tarball

- README.rst
remove confusing references to request params.
Users need to switch to matchers
> clean up docs

- CHANGES
- README.rst
- responses/__init__.py
- responses/tests/test_multithreading.py
closes #515 
based on the example in #515:
the issue why the error is raised, because `assert_all_requests_are_fired` checks for `call_count` on `Response` object.
in threading we may access `Response` in parallel, thus, `call_count > 1`. While users expects it to be `call_count == 1`.
Since we cannot ensure this, we need to Lock the thread
> Add  `threading.Lock()` 

- README.rst
some examples had wrong `code-block` syntax, see https://github.com/asottile/blacken-docs/issues/160
> fix rst examples

- CHANGES
- README.rst
- responses/__init__.py
- responses/tests/test_responses.py
> Allow configuration of passthrough during BaseResponse construction

- responses/tests/test_responses.py
- setup.py
switch pytest fixture because httpserver is a way more powerful compared to localserver and has a better documentation.
also, see https://github.com/pytest-dev/pytest-localserver/issues/43
> change pytest fixture to httpserver

- CHANGES
- mypy.ini
- responses/matchers.py
- responses/tests/test_matchers.py
closes #559 
I do not think we need to go for over-complicated comparisons of objects. User can extend functionality by applying custom matcher.
However, I do agree that lists should be supported as valid JSON
> Json matcher

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
replace exception by RetryError according to requests implementation: https://github.com/psf/requests/blob/177dd90f18a8f4dc79a7d2049f0a3f4fcc5932a0/requests/adapters.py#L549
closes #572
> fix retry error

- CHANGES
- README.rst
- setup.py
library since a long time requires "urllib3>=1.25.10"
if we looks at `requests` source code for v2.21.0 https://github.com/psf/requests/releases/tag/v2.21.0
we will see that they require  'urllib3>=1.21.1,<1.25',
https://github.com/psf/requests/blob/5a1e738ea9c399c3f59977f2f98b083986d6037a/setup.py#L47
thus, update our dependency to the higher requests. Docs as well
> Update `requests` dependency to the version of 2.22.0 or higher

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
related to #574 
After debugging I found the difference.
When not a raw response is provided, then error message will be `too many error responses`. While with raw response it is more explicit and mentions the error code: `too many 500 error responses`
I added tests that cover it.
> adjust error message when Retry is exhausted

- CHANGES
- responses/__init__.py
see comments in OriginalResponseShim. This urllib version is not used anyway.
same as #584
> remove OriginalResponseShim

- CHANGES
- responses/__init__.py
I think this is more pythonic way of doing shortcuts
> apply partialmethod to shortcuts

- CHANGES
- responses/__init__.py
With 0.22.0, mypy started to complain about constructions `rsps.calls[0].request` with an error
```
Item "List[Call]" of "Union[Call, List[Call]]" has no attribute "request"  [union-attr]
```
because it wasn't able to differentiate between the return types. I added `overload` annotation to handle that.
> Fix annotations of CallList

- responses/__init__.py
- responses/_recorder.py
- responses/tests/test_recorder.py
- setup.py
Replace the `toml` dependency that is unmaintained (last release in 2020) and does not implement TOML 1.0 with more modern libraries. Use the built-in `tomllib` module to load .toml files on Python 3.11, and its drop-in replacement `tomli` package on older versions of Python. For writing .toml files, use the `tomli-w` package.
> Use tomllib/tomli/tomli-w instead of unmaintained toml [WIP]

- .github/workflows/stackaid.yml
We saw an empty commit in https://github.com/getsentry/responses/commit/1d285695ada0065aacf1e10f4d5e770279e16361. Fixed in https://github.com/stackaid/generate-stackaid-json/commit/bbccf9adf6ab4acd69aa979b0cdc7e93a5e83d78.
> Upgrade StackAid action to pick up bugfix

- .github/workflows/ci.yml
[Example job](https://github.com/getsentry/responses/actions/runs/3329947398)
<details>
<summary>Screenshot</summary>
</details>
> ci(actions): Bump actions to resolve CI warnings

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
> attach request to custom exception

- responses/__init__.py
Attempt to use MonkeyType on responses.
Benefit seems minimal since this codebase already has lots of type hits.
> chore(typing): Try MonkeyType on modules in responses codebase

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
Basic setup for CodeQL to scan on PRs targeting master and once a week.
> Setup CodeQL

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
When multiple tests use assert_all_requests_are_fired=True and a test fails because mocks were not called, those mocks should be reset when the context manager exits.
Fixes #619
> Fix assert_all_requests_are_fired not reseting

- CHANGES
- README.rst
- responses/__init__.py
- responses/_recorder.py
- responses/tests/test_recorder.py
- setup.py
Added `responses.RequestsMock._parse_response_file` and  `responses._recorder.Recorder.dump_to_file` methods that allow users to override default parser to eg toml, json
Also, added tests that validate that both yaml and toml could be parsed.
Although, we add a test for toml parsing, I do not want to include methods for toml parsing directly to the lib, so, officially we support only YAML, all the rest implementation will rely on users
closes #615
> Change default recorder format to YAML

- CHANGES
- README.rst
- responses/tests/test_responses.py
- setup.py
closes #635 
I thought more about the issue #635. Actually, we are back compatible. 
`urllib3` now enforces content length validation. Our lib proposes auto calculation of content length. However, if the user wants to provide a header and the header does not match actual content length, then user gets an error. 
Which is expected from the new `urllib3`
> fix test compatibility with urllib3

- CHANGES
add notice that python 3.7 will not be supported in the future versions of the lib
> python 3.7 notice

- CHANGES
- responses/__init__.py
Moving `unbound_on_send` outside of the function will allow users to override the method if they will need to without a need to rewrite the entire `start` method
> move unbound_send outside of the function

- responses/matchers.py
- responses/tests/test_matchers.py
Attempt at #651.
- Changes in `header_matcher` function.
- Instead of using simple list equality, it now checks for either regex or simple string check.
- Added tests `test_request_matches_headers_regex`, `test_request_matches_headers_regex_strict_match`
> [#651] regex compatability for headers matching

- .pre-commit-config.yaml
- responses/__init__.py
- responses/matchers.py
- responses/registries.py
- responses/tests/test_recorder.py
- responses/tests/test_responses.py
noticed a few python2isms so I figured I'd fix them
> modernize source with pyupgrade

- responses/matchers.py
- responses/tests/test_matchers.py
I just discovered `matchers` (absolute lifesaver in concurrent tests), but I currently need to disable gzip for the tests since it isn't supported ootb.
Ltmk if there are additional changed/updates/changelog entries etc. you want me to create 😄
> Support gzipped request.body in json_params_matcher

- responses/__init__.py
Currently `mypy` is raising an error on `master` branch
```
responses/__init__.py:1051:32: error: Incompatible types in assignment (expression has type "PreparedRequest", variable has type "Request | None")  [assignment]
```
I do not know why mypy thinks that it could be None
> fix mypy issue

- responses/__init__.py
Reverts getsentry/responses#674
I do not know why, but now it started to work back and CI fails on [master](https://github.com/getsentry/responses/actions/runs/6301576006/job/17106907833) (facepalm)
> Revert "fix mypy issue"

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
closes #670 
allow to explicitly specify real send for each of the request mocks. That will unblock `moto` and allow `moto` users to use both `responses` and `moto` at the same time
> Added `real_adapter_send` parameter to `RequestsMock` 

- responses/__init__.py
change the order of dependencies installation to ensure that `urllib3` is not overwritten. Otherwise we have an issue that we do not test `urllib3<2`
@markstory 
I do not feel super comfortable with the order of installation of packages. In theory we can end up that we have artificial packages meaning that we override those packages that are specified in `setup.py` and we test not the real package. 
from CI I see the following error
```
types-requests 2.31.0.7 requires urllib3>=2
```
for me it feels that we still have to drop urllib3<2 since the upstream is moving towards it.
> fix coverage on master

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
> deduplicate content-type headers

- responses/__init__.py
updated `_form_response` function with more native handling by utilizing the correct `HTTPResponse` from `http` rather than from `urllib3`
> updated `_form_response` function

- CHANGES
- README.rst
- responses/__init__.py
- responses/matchers.py
- responses/tests/test_responses.py
Sometimes it is more convenient to get information about the calls made directly from the mockend request, instead of calculating the order of your calls in the global list (`responses.calls[n]`).
What do you think of such a possibility?
> Calls info in BaseResponse

- CHANGES
- mypy.ini
- responses/__init__.py
- responses/_recorder.py
- responses/matchers.py
- responses/tests/test_matchers.py
- responses/tests/test_multithreading.py
- responses/tests/test_recorder.py
- responses/tests/test_responses.py
* added typing in tests
* reverted overloads for activate
* Fix matchers typing
* Added status and body attributes to BaseResponse
closes #692
> Fix overloads and unlock mypy on tests

- CHANGES
- responses/__init__.py
- responses/tests/test_responses.py
- tox.ini
* Added pytest filter to ensure that we capture warnings as errors
* Revert socket change
* Added comment why this is the behaviour we have
* Added run on the test to fix coverage
closes #689 
closes #691
> Fix socket issues

- README.rst
It was missing the `urllib3.util.Retry` import.
> [README] Make "Validate Retry mechanism" code snippet complete

- responses/tests/test_registries.py
- responses/tests/test_responses.py
This resolved async test failures locally.
Refs #706
> Use pytest.mark.asyncio

- responses/__init__.py
- responses/tests/test_responses.py
This PR is a fix for this issue https://github.com/getsentry/responses/issues/708.
Basically when mocking a response to a HEAD request (which contains a content-length header), we do not pass the request_method. Which results in wrongfully raising a `ChunkedEncodingError`
> fix mocked HEAD response when content-length header is present

- CHANGES
- responses/matchers.py
- responses/tests/test_matchers.py
Hi!
This PR removes the `_create_key_val_str` and with it the sorting when displaying matchers errors
Let me know any change required!
Thank you 
Fixes GH-704
> fix(matchers): Don't sort failed matches when printing error message

- responses/matchers.py
- responses/tests/test_matchers.py
I use responses to mock APIs for applications. One of the API's used by my organization is an API for getting identifying information about about the "Owners" of AWS accounts. And the API just takes in the account number as the body of a GET request. 
here is an example of how I query the API from the command line
```
curl api.company.com/v1/accounts --data 12345
```
I have not been able to use responses to mock this API because this data is not JSON. I would like to contribute back a more flexible matcher for the bodies that just lets you match anything sent to an API endpoint.
> Add feature for allowing the body of a request to be matched Closes #716

- responses/__init__.py
- responses/tests/test_responses.py
Fixes #719 
Currently I've only dealt with file-like objects and ignored any of the other types that urllib3 supports (see https://github.com/urllib3/urllib3/blob/abbfbcb1dd274fc54b4f0a7785fd04d59b634195/src/urllib3/util/request.py#L220). This seems like an easy improvement since the alternative is keeping file objects in the call list, which are likely to be closed by the time the user gets to them. I don't know whether `responses` should go further though and try to convert every possible request body into a single format (probably `bytes`) to make it easier for the user to assert on.
> Read data from file-like objects in requests (#719)

- README.rst
- responses/__init__.py
- responses/tests/test_matchers.py
- responses/tests/test_responses.py
This makes it possible to import or access only RequestsMock (possibly via a pytest fixture) and still be able to easily access the matchers or assemble a Response object.
It also makes it easier to adopt pytest-responses which uses `responses` as the fixture variable which would conflict with an import of this module.
Add test cases that mask the existing imports and still access matchers or assemble a Response object via the RequestsMock instance.
Also recommend using pytest-responses for a pytest fixture. Rather than explaining how to roll your own in a Markdown snippet, recommend using the companion package to get a standard `responses` pytest fixture easily usable in test cases.
> Export names `matchers` and `Response` from RequestsMock instances

- pyproject.toml
- setup.py
Remove the tests/ directory from the wheel distribution of `responses`.  Wheels are intended to be a production release containing no tests.
Update setup.py removing `include_package_data` arg, which causes the wheel to contain the tests. Add a pyproject.toml with setup requires and a build backend. Remove references to the deprecated test command of setup tools.
> Remove tests from the wheel and simplify setup.py.

- README.rst
- responses/_recorder.py
- responses/tests/test_recorder.py
- tox.ini
I would like to use the recorded in the repl and record my requests.
This adds the code, tests and documentation for this.
> Recorder without decorator

- setup.py
fix #751
In the [PR](https://github.com/getsentry/responses/pull/746) the `include_package_data` flag was removed from `setup.py`.
This caused the `py.typed` marker file to also be removed, resulting in mypy errors:
```
Skipping analyzing "responses": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```
Using `package_data` we can pick specific files instead of everything (which was the motive for the latest change).
> fix #751: add package_data

- CHANGES
- responses/_recorder.py
- responses/tests/test_recorder.py
The intiial code skipped reorcding the content type and instead fell back to guessing. Now it only falls back to guessing if no explicit content type is provided.
- Closes #770
Before submitting this pull request, I have done the following:
> Current repository has 100% test coverage.
> Fix recording content_type

- responses/__init__.py
- responses/_recorder.py
- responses/tests/test_matchers.py
- responses/tests/test_responses.py
Fix up mypy errors that are present on master.
n/a
Before submitting this pull request, I have done the following:
> Current repository has 100% test coverage.
> Fix mypy errors in master
