responses.py
setup.py
test_responses.py

Feature: cookie handling

---

responses.py
test_responses.py

support for redirect chaining and history attribute for requests `allow_redirects=True` use cases.

support `allow_redirects=True`

---

responses.py

reproduced issue #62 on any requests <=2.2. 
It seems that _many_ more unit tests fail for requests <2.0, so I didn't even look at requests 0.x or 1.x ....

#62 is_redirect does not exist in requests 2.2 and earlier

---

.gitignore
tox.ini

@dcramer I do not know if you are interested by tox.
I just find it useful to deal with several python versions.
A next step would be to make travis relying on tox to reduce maintenance of 2 files.
I can do it if you like the idea.

tox configuration file

---

.travis.yml

- Test Requests 1.0, 2.0, latest, and master
- Switch to container builds

Expand testsuite

---

README.rst

Clarify docs about assert_all_requests_are_fired

---

responses.py
test_responses.py

This also includes a more general approach of handling the body from the match. Test added and all tests passes.

Implement streaming files

---

.travis.yml
Makefile
README.rst
responses.py
test_responses.py

fix: restore adding_headers compatibility

---

responses.py
test_responses.py

fix: count mocked errors in RequestsMock

---

responses.py
test_responses.py

This PR adds support for `responses.replace()`. The problem it is solving is the following: we usually have a base fixture of mocked API calls which we use like below in tests.
``` python
@pytest.mark.usefixtures('mock_api_calls')
def some_test():
pass
```
The fixture itself is defined as:
``` python
@pytest.fixture()
def mock_api_calls():
responses.add(responses.GET, 'http://someurl.com/one')
responses.add(responses.GET, 'http://someurl.com/two')
responses.add(responses.GET, 'http://someurl.com/three')
responses.add(responses.GET, 'http://someurl.com/four')
```
However, in the specific test we then want to change **one** of the API calls to return a different response. This wasn't possible previously, as `responses.add()` always appends to `_urls`. With `replace()`, we can now do:
``` …
```

Add support for removing and replacing existing mocked URLs

---

responses.py
test_responses.py

Unicode URLs were not supported in passthru mode, so this fixes that.

Add unicode support for passthru urls

---

README.rst

Added import of requests library.

Fix README examples with import of requests library

---

responses.py
test_responses.py

resolves https://github.com/getsentry/responses/issues/188

add support for custom patch target

---

responses.py

fix: Adapt to re.Pattern in Python 3.7

---

.artifacts/README
.gitignore
.pre-commit-config.yaml
.pre-commit-output/README
.travis.yml
.vscode/extensions.json
.vscode/settings.json
Makefile
responses.py
setup.py
test_responses.py

- Switch to Black
- Add VS Code configuration
- Apply Black to all files

build: Overhaul CI and autoformatting

---

.travis.yml

fix(build) Publish wheel and sdist artifacts.

---

CHANGES

This was missed, I couldn't tell what was changing as I was upgrading - some of my tests broke - so I had to read the git log to figure this out. THis will help future travellers.

Update changelog for 0.10.0 and 0.10.1

---

.travis.yml

Moved to https://github.com/requests/requests

Update git location of requests library

---

README.rst

Added pypi badge

---

README.rst
responses.py
test_responses.py

Add ability to pass a regex to add_passthru.

---

responses.py
test_responses.py

Change RequestsMock._on_request to catch BaseException.

---

README.rst
responses.py
test_responses.py

Return requested params in responses.calls[].request.

---

responses.py
test_responses.py

Fix the content type header in list based callback headers.
Refs #306

fix: Fix content-type in callbacks using list headers

---

setup.py

All tests pass here with coverage 5.2.

Allow coverage 5.x

---

README.rst

Fix typo in README.rst: Resposnes -> Responses

Fix typo: Resposnes -> Responses

---

responses.py
test_responses.py

Fixes https://github.com/getsentry/responses/issues/345

Improve ConnectionError error message.

---

responses.py

Fixes https://github.com/getsentry/responses/issues/354

Fixed HTTPHeaderDict import error.

---

README.rst
responses/__init__.py
responses/test_responses.py

Add upsert method.(#227)

---

README.rst

This is a simple example of usage inside a classic unittest setUp() clause

Add an exemple of unittest usage

---

setup.py

Add type stubs to package data.

---

.github/workflows/ci.yml
setup.py

Install more type libraries to try and get mypy to pass on github.

fix(build) Get typing build passing

---

responses/test_responses.py

tests for raw requests

---

responses/__init__.py
responses/test_responses.py

Add passthrough responses to CallList and increment call count

---

responses/__init__.py

remove functioned that was designed to include redirect resolving logic from requests.sessions.Session.
Now this logic is not used anymore in the code. For details see #63

clean up unused function

---

tox.ini

add mypy type validation as part of `tox` run

added mypy as part of the tox run

---

MANIFEST.in

I think we partially miss stub files

include all stub files in distribution

---

README.rst

we recent efforts we were able to push coverage to 100%
I think now we can proudly add badge with coverage :D

added badge for coverage

---

responses/__init__.py

PY2: _cookies_from_headers if python-future is installed

---

MANIFEST.in

fix MANIFEST.in

---

setup.py

bump coverage version

---

CHANGES
responses/__init__.py
responses/test_responses.py

remove some functions that are not necessary in py3+

clean up unused functions

---

MANIFEST.in
mypy.ini
responses/test_registries.py
responses/test_responses.py

move tests for registries to separate file

---

.pre-commit-config.yaml
Makefile
responses/__init__.py
responses/__init__.pyi
responses/matchers.py
responses/registries.py
responses/test_matchers.py
responses/test_registries.py
responses/test_responses.py

* added `isort` pre-commit hook to have readable imports
* bump pre-commit version in Makefile
otherwise it is a mess in imports, I cannot find where and what we import :D
let's merge it after #462, #477, #487, #489

added isort pre-commit hook

---

CHANGES
responses/__init__.py
responses/test_responses.py

change logic of _get_url_and_path to comply with RFC 3986

---

README.rst
responses/tests/test_responses.py

closes #152 
rendered RST: https://github.com/beliaev-maksim/responses/tree/mbeliaev/redirects#url-redirection

add redirections example and test

---

responses/tests/test_matchers.py
responses/tests/test_responses.py

master, 37 minor issues
this PR, 11:

minor test refactoring

---

README.rst
responses/tests/test_responses.py

added documentation and tests how to use requestmock as mock.patch

---

.pre-commit-config.yaml
README.rst

adds black style to the examples in the readme

added blacken docs pre-commit hook

---

.pre-commit-config.yaml

remove precommit hook for stub files

---

CHANGES
responses/__init__.py
responses/tests/test_recorder.py

[BETA] replay responses from toml files.

---

.github/workflows/stackaid.yml

Part of https://github.com/getsentry/team-ospo/issues/37.

Add StackAid config file

---

README.rst

document supported arguments

---

CHANGES
responses/__init__.py
responses/tests/test_responses.py

Fix issue with custom adapters 

---

responses/tests/test_responses.py

* move all passthru functions into one class
* rewritten test for `test_passthru_does_not_persist_across_tests`. Instead of overriding `_real_send` we rely on `httpserver` as other tests do

refactor passthru test functions

---

responses/tests/test_recorder.py
responses/tests/test_responses.py

Fix deprecation warnings from pytest related to setup and teardown deprecations.

Fix pytest warnings

---

.github/workflows/ci.yml
CHANGES
setup.py
tox.ini

added support for Python 3.13

---

responses/__init__.py

Before submitting this pull request, I have done the following:
> Current repository has 100% test coverage.

fix coverage
